export const APPLICATION_STATUS = {
  REQUESTED_ONBOARDING: 'REQUESTED_ONBOARDING',
  ACCEPTED: 'ACCEPTED', 
  OFFLINE_PROCESSING: 'OFFLINE_PROCESSING',
  ONBOARDED: 'ONBOARDED',
  PENDING_VENDOR_REVIEW: 'PENDING_VENDOR_REVIEW',
  LIVE: 'LIVE',
  REJECTED: 'REJECTED',
  REQUESTED_CHANGES: 'REQUESTED_CHANGES'
} as const;

type ApplicationStatus = typeof APPLICATION_STATUS[keyof typeof APPLICATION_STATUS];